# Generated by Django 4.2 on 2023-05-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Finished',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='ALREADY READ', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
            ],
        ),
        migrations.CreateModel(
            name='Goalnumber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('goal', models.CharField(max_length=100)),
            ],
        ),
    ]
