# Generated by Django 4.1 on 2023-03-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "username",
                    models.CharField(max_length=255, unique=True, verbose_name="账号"),
                ),
                ("password", models.CharField(max_length=255, verbose_name="密码")),
                ("email", models.EmailField(max_length=254, verbose_name="邮箱")),
                ("created_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={"verbose_name": "用户", "verbose_name_plural": "用户",},
        ),
    ]
