# Generated by Django 4.2 on 2023-05-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='count_score',
            fields=[
                ('game_user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='game_questions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=1000, null=True)),
                ('question', models.CharField(default='', max_length=1000, null=True)),
                ('opt1', models.CharField(default='', max_length=1000, null=True)),
                ('opt2', models.CharField(default='', max_length=1000, null=True)),
                ('opt3', models.CharField(default='', max_length=1000, null=True)),
                ('opt4', models.CharField(default='', max_length=1000, null=True)),
                ('answer', models.CharField(default='', max_length=1000, null=True)),
            ],
        ),
    ]
