# Generated by Django 4.1 on 2023-03-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('publisher', models.CharField(max_length=50)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(max_length=50)),
                ('avg_rating', models.FloatField()),
                ('total_number_reader', models.IntegerField()),
                ('total_number_sale', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
