# Generated by Django 4.2 on 2023-05-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('isbn', models.CharField(default='unknown', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('publication_date', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
                ('url', models.CharField(default='unknown', max_length=1000)),
                ('category', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('description', models.CharField(default='unknown', max_length=5000)),
            ],
        ),
    ]
