# Generated by Django 4.1 on 2023-03-31 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="book", name="avg_rating",),
        migrations.RemoveField(model_name="book", name="description",),
        migrations.RemoveField(model_name="book", name="total_number_reader",),
        migrations.RemoveField(model_name="book", name="total_number_sale",),
        migrations.AddField(
            model_name="book",
            name="isbn",
            field=models.CharField(default="unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="book",
            name="url",
            field=models.CharField(default="unknown", max_length=1000),
        ),
        migrations.AlterField(
            model_name="book",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
