# Generated by Django 4.1 on 2023-03-31 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookapp", "0002_remove_book_avg_rating_remove_book_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="publication_date",
            field=models.CharField(max_length=50),
        ),
    ]
